### ISSUE TITLE
Cannot export files

### ISSUE THREAD

**Issue by jinshuqishi2019** [danburzo/percollate#158]
### Environment

* Operating System: Debian10
* `node --version`:v18.17.0
* `npm --version`: 9.6.7
* `percollate --version`:v4.0.2

### Description
I have a folder with a lot of html files in it, so I'm trying to use the command to convert the html to the corresponding epub file.
```
find 100/*.html | xargs -L1 percollate epub

```

But I found that some of the conversions were successful but the others were not.

```
guang@pdf:~/110$ ls
2.epub  25-5.epub
guang@pdf:~/110$ percollate epub ../100/1.html
Fetching: ../100/1.html ✓
Enhancing web page: ../100/1.html ✓
Saving EPUB...
15043 total bytes, archive closed
Saved EPUB: 25-5.epubguang@pdf:~/110$ ls
2.epub  25-5.epub
```

```
guang@pdf:~/110$ percollate epub ../100/1.html -o 1.epub
Fetching: ../100/1.html ✓
Enhancing web page: ../100/1.html ✓
Saving EPUB...
15043 total bytes, archive closed
Saved EPUB: 1.epubguang@pdf:~/110$ ls
1.epub  2.epub  25-5.epub
```
What should I do to run the program correctly?
[1.html.zip](https://github.com/danburzo/percollate/files/12247995/1.html.zip)

**Comment by danburzo** [comment]
If you don’t see any particular errors, it may be that multiple items are outputting to the same `.epub` filename, overwriting each other. Percollate does not check if a file exists before writing to disk. 

One way I would approach it is to output to the corresponding epub file based on the original filename. Something like: 

```
find *.html | sed "p;s/\.html/\.epub/" | tail -r | xargs -L2 percollate epub -o
```

**Comment by jinshuqishi2019** [comment]
Very good, the commands you gave need a little modification to work.
```
find *.html | sed "p;s/\.html/\.epub/" | tac| xargs -L2 percollate epub -o
```
Now I want to generate epub from offline html for reading, one problem I found using this tool is that it can't handle this image format.

```
https://cubox.pro/c/filters:no_upscale()?valid=false&imageUrl=https%3A%2F%2Fpicx.zhimg.com%2F50%2Fv2-a6985ab263c4203730bb802c71b2dc90_720w.jpg%3Fsource%3D1940ef5c
```

Even if I use a command like this
```
 percollate epub 1.html -o 1.epub --inline
```
What can I do to solve this problem to make it work

**Comment by jinshuqishi2019** [comment]
There is also a problem when I synthesize multiple html files into one epub file, this problem occurs, but when I convert one html to one epub there is no problem.
```
percollate epub 100/*.html -o 100.epub
```

```
 Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263
                    throw new Error(`Could not find Chromium (rev. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/guang/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263:27)
    at ChromeLauncher.executablePath (file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:176:25)
    at ChromeLauncher.computeLaunchArguments (file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:93:37)
    at async ChromeLauncher.launch (file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:57:28)
    at async file:///usr/local/node/lib/node_modules/percollate/index.js:875:20

Node.js v18.17.0


```

**Comment by danburzo** [comment]
Hi @jinshuqishi2019, I'm going to close this issue as we seemed to have figured out what caused the original problem. Can you please open separate issues for these last two problems you encountered?
