### ISSUE TITLE
Multiple html files are synthesized into a single epub file with errors

### ISSUE THREAD

**Issue by jinshuqishi2019** [danburzo/percollate#160]
### Environment

Operating System: Debian10
node --version:v18.17.0
npm --version: 9.6.7
percollate --version:v4.0.2

### Description
Hello！
There is a problem when I synthesize multiple html files into one epub file, this problem occurs, but when I convert one html to one epub there is no problem.

```
percollate epub 100/*.html -o 100.epub
```

```
 Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263
                    throw new Error(`Could not find Chromium (rev. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/guang/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263:27)
    at ChromeLauncher.executablePath (file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:176:25)
    at ChromeLauncher.computeLaunchArguments (file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:93:37)
    at async ChromeLauncher.launch (file:///usr/local/node/lib/node_modules/percollate/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:57:28)
    at async file:///usr/local/node/lib/node_modules/percollate/index.js:875:20

Node.js v18.17.0


```

[html.zip](https://github.com/danburzo/percollate/files/12259112/html.zip)

**Comment by danburzo** [comment]
Can you let me know which install method you used for `percollate`? If you reinstall it with:

```bash
npm uninstall -g percollate
npm install -g percollate
```

...does the problem still happen? Does percollate work in other situations, and only this specific command produces the Chromium error?

**Comment by jinshuqishi2019** [comment]
Nice!Thank you very much!
Reinstalling percollate solved my problem.
I also started out using npm for the installation, which may have conflicted with the program installed later.
All in all, thanks for the help.

**Comment by danburzo** [comment]
Great to hear, cheers!
