### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by MatthewShields** [danburzo/percollate#24]
Installed globally via NPM however when trying to run (any site) the following error is received:

/usr/local/lib/node_modules/percollate/index.js:31
async function cleanup(url) {
           ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

**Comment by danburzo** [comment]
Can you let me know your Node.js version? (`node --version` in the command-line). `percollate` uses syntax that's been introduced in later Node versions (8+). I was hoping the `engines` config in `package.json` will result in a sort of warning when trying to install on older node versions, but I think that's not the case?

**Comment by YohannParis** [comment]
I had the same issue, and following your comment I checked my Node version which was `6.5.2`. I updated to the latest version and all works well.

**Comment by danburzo** [comment]
I'm going to close this. I've added a note about the required Node version to the README file.
