### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by jaspal747** [danburzo/percollate#30]
Tried running percollate --v, returns the "Unexpected token function" error.

percollate/index.js:31
async function cleanup(url) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by danburzo** [comment]
As mentioned in this thread (and now in the README), `percollate` needs Node v8 or later. Can you let me know if upgrading your Node version fixes the problem? https://github.com/danburzo/percollate/issues/24
