### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by aheadlcx** [danburzo/percollate#45]
When I put percollate pdf --output as32.pdf https://github.com/danburzo/percollate , get this error.

````java
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/percollate/cli.js:5:40)
````

**Comment by danburzo** [comment]
Thanks for reporting! Can you let me know your node.js version?

**Comment by aheadlcx** [comment]
v8.0.0
@danburzo

**Comment by tanmayrajani** [comment]
I think `8.0.0` may just need the `--harmony` flag. 

Although, we might want to update the README

**Comment by aheadlcx** [comment]
@tanmayrajani  Adding this flag still not work.
The command is that 'percollate pdf --output --harmony as32.pdf https://github.com/danburzo/percollate' and return following log:

````java
/usr/local/lib/node_modules/percollate/index.js:59
	return { ...parsed, url };
	         ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/percollate/cli.js:5:40)
````

**Comment by aheadlcx** [comment]
@tanmayrajani Thanks and looking forward to your next commit.

**Comment by danburzo** [comment]
I think the `node --harmony` thing is trickier, since [it doesn't seem to be supported everywhere](https://github.com/SpencerCDixon/redux-cli/issues/39). We may just have to bump up the Node.js version requirement. I'm not sure how to find out the minimum Node version required by the code, but https://node.green/ suggest it's 8.6.0?

**Comment by aheadlcx** [comment]
@danburzo Thanks for your answer.

**Comment by tanmayrajani** [comment]
> We may just have to bump up the Node.js version requirement. I'm not sure how to find out the minimum Node version required by the code, but https://node.green/ suggest it's 8.6.0?

That's probably a good idea. I see `got` follows the same:

https://github.com/sindresorhus/got/blob/8d2e91171509bc2aec71c4483978cfd421ebcf1d/package.json#L8-L10

**Comment by danburzo** [comment]
Made the change in the above commit. Will be publishing a new version on npm once we get in a few more fixes. Thanks both for the assistance!
