### ISSUE TITLE
Error while saving pdf

### ISSUE THREAD

**Issue by butu5** [danburzo/percollate#80]
https://medium.com/machine-learning-for-humans/why-machine-learning-matters-6164faf1df12
https://medium.com/@v_maini/supervised-learning-740383a2feab
https://medium.com/@v_maini/supervised-learning-2-5c1c23f3560d
https://medium.com/@v_maini/supervised-learning-3-b1551b9c4930

```log
/ Saving PDF(node:1512) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\Users\...\github\percollate\node_modules\puppeteer\lib\FrameManager.js:1230:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\...\github\percollate\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.goto (C:\Users\uc245524\github\percollate\node_modules\puppeteer\lib\Page.js:579:49)
    at Page.<anonymous> (C:\Users\...\github\percollate\node_modules\puppeteer\lib\helper.js:145:23)
    at bundle (C:\Users\...\github\percollate\index.js:201:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by butu5** [comment]
Increased the timeout. Worked fine now.
https://github.com/butu5/percollate/commit/13db308181d3e17bd2a25145103bb09f0ac8442f

**Comment by butu5** [comment]
I am thinking pulling images takes time. Just thinking.. will debug more.

**Comment by danburzo** [comment]
I've increased the timeout to 2 minutes, although it seems unlikely that it needs so much time for fetching. It may be that it hangs on a request we're not seeing. In any case, I've added logging for the individual resources.
